name: CI Build InvertMouse Driver

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, ARM64]
    runs-on: windows-2022
    env:
      Solution_Path: src\InvertMouseDriver\InvertMouse.sln

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build solution
      run: |
        msbuild ${{ env.Solution_Path }} -p:Configuration:${{ env.Configuration }} -p:Platform:${{ env.Platform }}
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: InvertMouse-${{ matrix.platform }}
        path: |
          **/${{ matrix.platform }}/Release/InvertMouse/InvertMouse.sys
          **/${{ matrix.platform }}/Release/InvertMouse/InvertMouse.inf
